### ISSUE TITLE
About source code of models

### ISSUE THREAD

**Issue by kuraga** [sismetanin/sentiment-analysis-in-russian#1]
> To download fine-tuned models for Russian, please follow the link https://yadi.sk/d/Xp5vLG_5xCQL-Q.

@sismetanin , am I right that these models doesn't have source code and can't be re-trained?

Thanks!

**Comment by sismetanin** [comment]
Hey @kuraga, you can find source code on the official pages: [BERT repo](https://github.com/google-research/bert), [RuBERT](http://docs.deeppavlov.ai/en/master/features/models/bert.html),  [USE](https://tfhub.dev/google/universal-sentence-encoder-multilingual/3), and [USE-Large](https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3).
